### ISSUE TITLE
Blogs pessoais constam na lista 

### ISSUE THREAD

**Issue by LFeh** [cerebrobr/comunidade#21]
Pessoal,

Essa lista não era só para blogs colaborativos?

Existem alguns blogs pessoais, como o do @fdaciuk e do Brad Frost.

summon @cerebrobr/editores

**Comment by fdaciuk** [comment]
Na real eu acho que independe. Na lista deve constar blogs que contribuem para a comunidade de alguma forma. Inclusive está faltando vários aí nessa lista, como o seu @LFeh, o do Wililan Justen, do @vitorbritto, etc., pois todos são blogs direcionados para a comunidade, e não tanto para tratar de assuntos pessoais :)

**Comment by nicholasess** [comment]
Quem vai mandar o PR?
hahahahaha

**Comment by LFeh** [comment]
@fdaciuk, também acho legal adicionar todos os blogs, mesmo sendo pessoais.

Todos concordam?

**Comment by nicholasess** [comment]
+1

**Comment by LFeh** [comment]
c/c @vitorbritto

**Comment by thulioph** [comment]
Pode crer, adicionar todos os blogs seria a melhor idéia.. Tem conteúdo bom em todos, nem que seja um único post, então vale a pena citar :)

+1

**Comment by vitorbritto** [comment]
Estou de acordo.

**Comment by LFeh** [comment]
\o
