### ISSUE TITLE
Sites indisponíveis

### ISSUE THREAD

**Issue by theuves** [cerebrobr/comunidade#29]
Sites que estão indisponíveis:

- [Coding on Weekend](http://codingonweekend.com.br/) (Em  cursos.md)
- [Piratas da Internet](http://www.piratasdainternet.com.br/) (Em casts.md)
- [DevCast](http://devcastbrasil.com/) (Em casts.md)

**Comment by fdaciuk** [comment]
@theuves consegue mandar um pull request removendo eles?

**Comment by theuves** [comment]
@fdaciuk Sim #31

**Comment by Marcelosilva10** [comment]
Achei alguns aqui também.

##Back-End##

http://www.tudoparawordpress.com.br/ Alterado - http://tudoparawp.com.br/

##Front-End##

http://www.frontendbrasil.com.br/ (Quebrado?)
http://ww2.oderdenge.com/ (Quebrado?)
http://blog.lessmilk.com/ (O que Aconteceu aqui?)
http://pedronauck.com/ (Quebrado?)
http://blog.thulioph.com/ (Quebrado?)

**Comment by fdaciuk** [comment]
@Marcelosilva10, pode enviar um pull request atualizando esses links que você encontrou? =)

**Comment by Marcelosilva10** [comment]
Claro envio com todos prazer.
