### ISSUE TITLE
Será que seria bom compartilhar aqui tbm o CodeNine?

### ISSUE THREAD

**Issue by Marcelosilva10** [cerebrobr/comunidade#36]
https://c9.io/

É uma ide online.

**Comment by nicholasess** [comment]
@Marcelosilva10 estaria mais ligado as IDE's, não vejo um tópico que se encaixa.

**Comment by Marcelosilva10** [comment]
Sim em uma Ide's on lines

**Comment by nicholasess** [comment]
Manda um PR para [esse repositório](https://github.com/cerebrobr/ferramentas/blob/pt-BR/sections/online.md#social-code)

**Comment by Marcelosilva10** [comment]
@nicholasess isso entra como Croos ou como IDE Web?

**Comment by nicholasess** [comment]
Social Code

**Comment by Marcelosilva10** [comment]
Certo vou fzr um pr aqui, viu o Free Code está fora do ar parece.

**Comment by nicholasess** [comment]
Tem como ver na listagem os sites que estão com link fora do ar e mandar um PR com tudo certo?

**Comment by Marcelosilva10** [comment]
ok podeixar viu como eu descrevo o commit?

**Comment by Marcelosilva10** [comment]
Obervação aproveitei e coloquei tudo na ordem alfabética também!

**Comment by nicholasess** [comment]
[Veja nosso guia](https://github.com/cerebrobr/cerebro/blob/master/CONTRIBUTING.md#recomendações-1)

**Comment by Marcelosilva10** [comment]
@nicholasess subi o pull request
ve lá plz

**Comment by nicholasess** [comment]
@Marcelosilva10 não tem nenhum PR

**Comment by nicholasess** [comment]
você mandou no https://github.com/vitorbritto/dev-list, é o do cerebrobr: https://github.com/vitorbritto/dev-list

**Comment by Marcelosilva10** [comment]
@nicholasess o que faço?

**Comment by nicholasess** [comment]
Forka o repositório certo e manda as atualizações

**Comment by Marcelosilva10** [comment]
OK, @nicholasess mandei veja aí.
