### ISSUE TITLE
Site que sairam do ar e um com link alterado.

### ISSUE THREAD

**Issue by Marcelosilva10** [cerebrobr/comunidade#37]
Boa noite observei que tem alguns site que foram removidos do ar e um deles foi alterado seu link, está aí embaixo.

##Back-End##

http://www.tudoparawordpress.com.br/ Alterado - http://tudoparawp.com.br/

##Front-End##

http://www.frontendbrasil.com.br/ (Quebrado?)
http://ww2.oderdenge.com/ (Quebrado?)
http://blog.lessmilk.com/ (O que Aconteceu aqui?)
http://pedronauck.com/ (Quebrado?)
http://blog.thulioph.com/ (Quebrado?)

**Comment by nicholasess** [comment]
@Marcelosilva10 poderia enviar um PR com as correções?
Abs

**Comment by Marcelosilva10** [comment]
podeixar comigo.

**Comment by Marcelosilva10** [comment]
Foi feito e ninguém subiu ainda :(

**Comment by LFeh** [comment]
Cade?

**Comment by fdaciuk** [comment]
@Marcelosilva10 mandou PR? Joga o link aqui ou marca alguém lá no seu PR =)

**Comment by LFeh** [comment]
Acho que ele fez.

**Comment by Marcelosilva10** [comment]
Fiz sim @LFeh você deu um merge esses dias.
